import React,{useState}from'react';import{createRoot}from'react-dom/client';import{HashRouter,Routes,Route,Link,useParams}from'react-router-dom';import{ArrowUpRight,Play,Menu,X}from'lucide-react';import{releases,artists,events,mixes}from'./data/content';import'./styles.css';

const Cover=({r,i=0})=><div className={'cover c'+(i%6)}>{r.artwork&&<img src={r.artwork} alt={`${r.artist} — ${r.title}`} loading="lazy"/>}<span>{r.catalog}</span><div className="coverHover"><b>{r.artist}<br/>{r.title}</b><ArrowUpRight/></div></div>;
function Header(){const[open,setOpen]=useState(false);return <nav><Link className="brand logoBrand" to="/"><img src={`${import.meta.env.BASE_URL}assets/spacedisco+logo+sq+white.webp`} alt="Spacedisco Records"/></Link><div className={'navlinks '+(open?'open':'')}>{[['Music','/music'],['Artists','/artists'],['Events','/events'],['Mixes','/mixes'],['Demos','/demos']].map(([n,p])=><Link onClick={()=>setOpen(false)} key={p} to={p}>{n}</Link>)}</div><button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></nav>}
const PageHead=({n,kicker,children})=><section className="pageHead"><small>{kicker}</small><h1>{n}</h1>{children}</section>;
function Home(){return <><section className="hero"><div className="eyebrow">INDEPENDENT HOUSE MUSIC · TORONTO · EST. 2006</div><h1>SPACE<br/>DISCO<span>®</span></h1><div className="heroBottom"><p>HOUSE MUSIC<br/>FROM EARTH + BEYOND.</p><div className="current"><small>CURRENT TRANSMISSION / {releases[0].catalog}</small><h2>{releases[0].artist}<br/>{releases[0].title}</h2><Link className="button" to={'/music/'+releases[0].slug}><Play size={18} fill="currentColor"/> ENTER RELEASE</Link></div></div><div className="orbit"/></section><div className="ticker"><div>SPACEDISCO / NEW MUSIC / TORONTO / KEEP DANCING / HOUSE MUSIC FROM EARTH + BEYOND / &nbsp; SPACEDISCO / NEW MUSIC / TORONTO / KEEP DANCING /</div></div><section className="section"><header><div><small>01 / CATALOGUE</small><h2>NEW SIGNALS</h2></div><Link to="/music">EXPLORE ALL <ArrowUpRight/></Link></header><ReleaseGrid items={releases.slice(0,6)}/></section><section className="artists section"><header><div><small>02 / ROSTER</small><h2>ARTISTS</h2></div></header><ArtistList/></section><FeatureGrid/><DemoCTA/></>}
function ReleaseGrid({items}){return <div className="releaseGrid">{items.map((r,i)=><Link className="release" to={'/music/'+r.slug} key={r.catalog}><Cover r={r} i={i}/><small>{r.catalog} · {r.date||r.year}</small><h3>{r.artist}</h3><p>{r.title}</p></Link>)}</div>}
function ArtistList(){return <div className="artistGrid">{artists.map((a,i)=><Link className="artistCard" key={a.slug} to={'/artists/'+a.slug}><div className="artistImage">{a.image?<img src={a.image} alt="" loading="lazy"/>:<div className="artistFallback">SDR</div>}<span>{String(i+1).padStart(2,'0')}</span></div><div className="artistMeta"><h3>{a.name}</h3><small>{a.location}</small><ArrowUpRight/></div></Link>)}</div>}
function Music(){return <><PageHead n="MUSIC" kicker="01 / CATALOGUE"><p>THE COMPLETE SPACEDISCO SIGNAL. NEW HOUSE MUSIC, CLUB TOOLS AND DEEP-CUT TRANSMISSIONS.</p></PageHead><section className="section"><ReleaseGrid items={releases}/></section></>}
function Release(){const{slug}=useParams();const r=releases.find(x=>x.slug===slug);if(!r)return <NotFound/>;const i=releases.indexOf(r);return <section className="detail"><div><small>{r.catalog} / {r.year} / {r.genre}</small><h1>{r.artist}<br/><em>{r.title}</em></h1><p>SPACEDISCO RECORDS · TORONTO / WORLDWIDE</p><div className="actions"><button><Play size={18}/> PLAY PREVIEW</button><a className="storeButton outline" href={r.beatport} target="_blank" rel="noreferrer">BEATPORT <ArrowUpRight size={18}/></a><a className="storeButton outline" href={r.traxsource} target="_blank" rel="noreferrer">TRAXSOURCE <ArrowUpRight size={18}/></a></div></div><Cover r={r} i={i}/></section>}
function Artists(){return <><PageHead n="ARTISTS" kicker="02 / ROSTER"><p>THE PEOPLE BEHIND THE SIGNAL.</p></PageHead><section className="section"><ArtistList/></section></>}
function Artist(){const{slug}=useParams();const a=artists.find(x=>x.slug===slug);if(!a)return <NotFound/>;const rs=releases.filter(r=>r.artist.toUpperCase()===a.name);return <><section className="artistHero hasPhoto"><div className="artistHeroCopy"><small>SPACEDISCO ARTIST / {a.location}</small><h1>{a.name}</h1><p>{a.bio}</p><a className="artistInquiry" href="mailto:SpacediscoRecords@gmail.com">BOOKING / INQUIRIES <ArrowUpRight size={18}/></a></div>{a.image&&<div className="artistHeroPhoto"><img src={a.image} alt=""/></div>}<div className="artistGhost">{a.name}</div></section><section className="section"><header><div><small>DISCOGRAPHY</small><h2>ON THE LABEL</h2></div></header>{rs.length?<ReleaseGrid items={rs}/>:<p className="empty">CATALOGUE SIGNAL INCOMING.</p>}</section></>}
function Events(){return <><PageHead n="EVENTS" kicker="03 / IRL"><p>FROM THE LABEL TO THE ROOM. UPCOMING SPACEDISCO TRANSMISSIONS.</p></PageHead><section className="listPage">{events.map((e,i)=><article key={i}><b>{e.date}</b><h2>{e.city}</h2><div><strong>{e.venue}</strong><p>{e.detail}</p></div><ArrowUpRight/></article>)}</section></>}
function Mixes(){return <><PageHead n="MIXES" kicker="04 / BROADCASTS"><p>RADIO, GUEST MIXES AND AFTER-HOURS TRANSMISSIONS.</p></PageHead><section className="mixGrid">{mixes.map(m=><article key={m.number}><small>EPISODE {m.number}</small><div className="disc"><Play fill="currentColor"/></div><h2>{m.title}</h2><p>{m.artist} · {m.length}</p><button>LISTEN NOW <ArrowUpRight/></button></article>)}</section></>}
function Demos(){return <><PageHead n="DEMOS" kicker="05 / SEND A SIGNAL"><p>WE WANT MUSIC WITH IDENTITY. HOUSE MUSIC THAT MOVES PEOPLE AND DOESN'T SOUND LIKE EVERYTHING ELSE.</p></PageHead><section className="demoPage"><div><small>BEFORE YOU SEND</small><h2>MAKE IT<br/>IMPOSSIBLE<br/>TO IGNORE.</h2></div><div><p>Send private streaming links only. Include a short introduction, artist name and contact information. Please don't attach large audio files.</p><a className="button" href="mailto:demos@spacediscorecords.com">SUBMIT YOUR DEMO <ArrowUpRight/></a></div></section></>}
function FeatureGrid(){return <section className="world"><Link to="/mixes"><small>03 / BROADCASTS</small><h2>RADIO<br/>+ MIXES</h2><ArrowUpRight/></Link><Link to="/events"><small>04 / IRL</small><h2>EVENTS</h2><ArrowUpRight/></Link><Link className="acid" to="/music"><small>05 / CATALOGUE</small><h2>SELECTIONS</h2><ArrowUpRight/></Link></section>}
function DemoCTA(){return <section className="demo"><small>DEMO SUBMISSIONS</small><h2>YOUR MUSIC BELONGS HERE</h2><div><p>Send us something we can't ignore. Fresh talent and forward-thinking house music.</p><Link className="button dark" to="/demos">SUBMIT YOUR DEMO <ArrowUpRight/></Link></div></section>}
function NotFound(){return <PageHead n="404" kicker="SIGNAL LOST"><p>THAT TRANSMISSION DOESN'T EXIST. <Link to="/">RETURN HOME →</Link></p></PageHead>}
function Footer(){return <footer><h2>KEEP<br/>DANCING.</h2><div><img className="footerLogo" src={`${import.meta.env.BASE_URL}assets/spacedisco+logo+sq+white.webp`} alt="Spacedisco Records"/><p>Independent house music from Earth + beyond.</p><p>INSTAGRAM · SOUNDCLOUD · SPOTIFY · YOUTUBE</p><small>© 2026 SPACEDISCO RECORDS · TORONTO / WORLDWIDE</small></div></footer>}
function App(){return <HashRouter><Header/><Routes><Route path="/" element={<Home/>}/><Route path="/music" element={<Music/>}/><Route path="/music/:slug" element={<Release/>}/><Route path="/artists" element={<Artists/>}/><Route path="/artists/:slug" element={<Artist/>}/><Route path="/events" element={<Events/>}/><Route path="/mixes" element={<Mixes/>}/><Route path="/demos" element={<Demos/>}/><Route path="*" element={<NotFound/>}/></Routes><Footer/></HashRouter>}
createRoot(document.getElementById('root')).render(<App/>);