import React,{useState,useEffect,useRef}from'react';import{createRoot}from'react-dom/client';import{HashRouter,Routes,Route,Link,useParams}from'react-router-dom';import{ArrowUpRight,Play,Menu,X}from'lucide-react';import{releases,artists,events,mixes,musicCatalogue}from'./data/content';import'./styles.css';
import spacediscoLogo from '../assets/spacedisco+logo+sq+white.webp';

const Cover=({r,i=0})=><div className={'cover c'+(i%6)}>{r.artwork&&<img src={r.artwork} alt={`${r.artist} — ${r.title}`} loading="lazy"/>}<span>{r.catalog}</span><div className="coverHover"><b>{r.artist}<br/>{r.title}</b><ArrowUpRight/></div></div>;
function Header(){const[open,setOpen]=useState(false);return <nav><Link className="brand logoBrand" to="/"><img src={spacediscoLogo} alt="Spacedisco Records"/></Link><div className={'navlinks '+(open?'open':'')}>{[['Music','/music'],['Artists','/artists'],['Events','/events'],['Mixes','/mixes'],['Demos','/demos']].map(([n,p])=><Link onClick={()=>setOpen(false)} key={p} to={p}>{n}</Link>)}</div><button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></nav>}
function Reveal({children,className='',delay=0}){const ref=useRef(null);useEffect(()=>{const el=ref.current;if(!el)return;const io=new IntersectionObserver(([entry])=>{if(entry.isIntersecting){el.classList.add('is-visible');io.unobserve(el)}},{rootMargin:'0px 0px -8% 0px',threshold:.08});io.observe(el);return()=>io.disconnect()},[]);return <div ref={ref} className={'reveal '+className} style={{'--reveal-delay':delay+'ms'}}>{children}</div>}
const PageHead=({n,kicker,children})=><section className="pageHead"><small>{kicker}</small><h1>{n}</h1>{children}</section>;
function Home(){const latestRelease=releases[0];const latestEvent=events[0];return <><section className="latestHero"><div className="latestPanel releaseFeature"><div className="latestCopy"><small>01 / LATEST RELEASE · {latestRelease.catalog}</small><h1>{latestRelease.artist}<br/><em>{latestRelease.title}</em></h1><p>{latestRelease.date||latestRelease.year} · {latestRelease.genre}</p><Link className="button" to={'/music/'+latestRelease.slug}><Play size={18} fill="currentColor"/> ENTER RELEASE</Link></div><Link className="latestArtwork" to={'/music/'+latestRelease.slug}><Cover r={latestRelease}/></Link></div>{latestEvent&&<div className="latestPanel eventFeature"><div className="latestCopy"><small>02 / LATEST EVENT</small><h2>SPACEDISCO<br/>IRL</h2><p>THE LATEST EVENT SIGNAL, DIRECT FROM SPACEDISCO.</p>{latestEvent.link?<a className="button dark" href={latestEvent.link} target="_blank" rel="noreferrer">EVENT DETAILS <ArrowUpRight size={18}/></a>:<Link className="button dark" to="/events">VIEW EVENT <ArrowUpRight size={18}/></Link>}</div><Link className="latestArtwork" to="/events"><img src={latestEvent.image} alt="Latest Spacedisco event" loading="eager"/></Link></div>}</section><div className="ticker"><div>SPACEDISCO / NEW MUSIC / TORONTO / KEEP DANCING / HOUSE MUSIC FROM EARTH + BEYOND / &nbsp; SPACEDISCO / NEW MUSIC / TORONTO / KEEP DANCING /</div></div><Reveal><section className="section"><header><div><small>01 / CATALOGUE</small><h2>NEW SIGNALS</h2></div><Link to="/music">EXPLORE ALL <ArrowUpRight/></Link></header><ReleaseGrid items={releases.slice(0,6)}/></section></Reveal><Reveal><section className="artists section"><header><div><small>02 / ROSTER</small><h2>ARTISTS</h2></div></header><ArtistList items={artists.slice(0,6)}/></section></Reveal><Reveal><FeatureGrid/></Reveal><Reveal><DemoCTA/></Reveal></>}
function ReleaseGrid({items}){return <div className="releaseGrid">{items.map((r,i)=><Link className="release" to={'/music/'+r.slug} key={r.catalog}><Cover r={r} i={i}/><small>{r.catalog} · {r.date||r.year}</small><h3>{r.artist}</h3><p>{r.title}</p></Link>)}</div>}
function ArtistList({items=artists}){return <div className="artistGrid">{items.map((a,i)=><Link className="artistCard" key={a.slug} to={'/artists/'+a.slug}><div className="artistImage">{a.image?<img src={a.image} alt="" loading="lazy"/>:<div className="artistFallback">SDR</div>}<span>{String(i+1).padStart(2,'0')}</span></div><div className="artistMeta"><h3>{a.name}</h3><small>{a.location}</small><ArrowUpRight/></div></Link>)}</div>}
function Music(){return <><PageHead n="MUSIC" kicker="01 / CATALOGUE"><p>THE COMPLETE SPACEDISCO SIGNAL. NEW HOUSE MUSIC, CLUB TOOLS AND DEEP-CUT TRANSMISSIONS.</p></PageHead><section className="musicCatalogue">{musicCatalogue.map((r,i)=>{const card=<><img src={r.artwork} alt={`Spacedisco release ${i+1}`} loading="lazy"/>{r.listen&&<b><Play size={16} fill="currentColor"/> LISTEN</b>}</>;const item=r.listen?<a href={r.listen} target="_blank" rel="noreferrer">{card}</a>:<article>{card}</article>;return <Reveal className="gridReveal" delay={(i%6)*55} key={r.artwork}>{item}</Reveal>})}</section></>}
function Release(){const{slug}=useParams();const r=releases.find(x=>x.slug===slug);if(!r)return <NotFound/>;const i=releases.indexOf(r);return <section className="detail"><div><small>{r.catalog} / {r.year} / {r.genre}</small><h1>{r.artist}<br/><em>{r.title}</em></h1><p>SPACEDISCO RECORDS · TORONTO / WORLDWIDE</p><div className="actions"><button><Play size={18}/> PLAY PREVIEW</button><a className="storeButton outline" href={r.beatport} target="_blank" rel="noreferrer">BEATPORT <ArrowUpRight size={18}/></a><a className="storeButton outline" href={r.traxsource} target="_blank" rel="noreferrer">TRAXSOURCE <ArrowUpRight size={18}/></a></div></div><Cover r={r} i={i}/></section>}
function Artists(){return <><PageHead n="ARTISTS" kicker="02 / ROSTER"><p>THE PEOPLE BEHIND THE SIGNAL.</p></PageHead><section className="section"><ArtistList/></section></>}
function Artist(){const{slug}=useParams();const a=artists.find(x=>x.slug===slug);if(!a)return <NotFound/>;const rs=releases.filter(r=>r.artist.toUpperCase()===a.name);return <><section className="artistHero hasPhoto"><div className="artistHeroCopy"><small>SPACEDISCO ARTIST / {a.location}</small><h1>{a.name}</h1><p>{a.bio}</p><a className="artistInquiry" href="mailto:SpacediscoRecords@gmail.com">BOOKING / INQUIRIES <ArrowUpRight size={18}/></a></div>{a.image&&<div className="artistHeroPhoto"><img src={a.image} alt=""/></div>}<div className="artistGhost">{a.name}</div></section><section className="section"><header><div><small>DISCOGRAPHY</small><h2>ON THE LABEL</h2></div></header>{rs.length?<ReleaseGrid items={rs}/>:<p className="empty">CATALOGUE SIGNAL INCOMING.</p>}</section></>}
function Events(){return <><PageHead n="EVENTS" kicker="03 / IRL"><p>FROM THE LABEL TO THE ROOM. EVENTS PULLED DIRECTLY FROM SPACEDISCO.</p></PageHead><section className="eventGrid">{events.map((e,i)=>{const card=<><img src={e.image} alt={`Spacedisco event ${i+1}`} loading="lazy"/><span>{String(i+1).padStart(2,'0')}</span>{e.link&&<b>TICKETS <ArrowUpRight size={18}/></b>}</>;const item=e.link?<a href={e.link} target="_blank" rel="noreferrer">{card}</a>:<article>{card}</article>;return <Reveal className="gridReveal" delay={(i%3)*80} key={e.image}>{item}</Reveal>})}</section></>}
function Mixes(){return <><PageHead n="MIXES" kicker="04 / BROADCASTS"><p>THE SPACEDISCO MIX ARCHIVE. RADIO, GUEST MIXES AND AFTER-HOURS TRANSMISSIONS.</p></PageHead><section className="mixArchive">{mixes.map((mix,i)=>{const card=<><img src={mix.image} alt={`Spacedisco mix ${i+1}`} loading="lazy"/><span>{mix.number}</span>{mix.link&&<b><Play size={16} fill="currentColor"/> LISTEN</b>}</>;const item=mix.link?<a href={mix.link} target="_blank" rel="noreferrer">{card}</a>:<article>{card}</article>;return <Reveal className="gridReveal" delay={(i%4)*65} key={mix.image}>{item}</Reveal>})}</section></>}
function Demos(){
  const demoEmail='SpacediscoRecords@gmail.com';
  const [artist,setArtist]=useState('');
  const [track,setTrack]=useState('');
  const [link,setLink]=useState('');
  const [note,setNote]=useState('');
  const subject=encodeURIComponent(`DEMO SUBMISSION — ${artist||'ARTIST'} — ${track||'TRACK'}`);
  const body=encodeURIComponent(`Artist: ${artist}\nTrack: ${track}\nPrivate streaming link: ${link}\n\nAbout the record / artist:\n${note}\n\nContact email:\n`);
  const ready=artist.trim()&&track.trim()&&/^https?:\/\//i.test(link.trim());
  return <><PageHead n="DEMOS" kicker="05 / SEND A SIGNAL"><p>SPACEDISCO IS LISTENING. SEND US YOUR BEST MUSIC DIRECTLY.</p></PageHead>
    <section className="demoSubmit">
      <div className="demoIntro">
        <small>DEMO TRANSMISSION / 001</small>
        <h2>SEND US<br/><em>THE ONE</em></h2>
        <p>The official Spacedisco demos page directs submissions to <strong>{demoEmail}</strong>. We’ve turned that into a cleaner submission flow so your email arrives organized and easy to review.</p>
        <div className="demoRules"><span>01</span><p>Send a private streaming link. SoundCloud, Dropbox, Drive or another accessible link works best.</p><span>02</span><p>Make sure the link actually plays and permissions are enabled.</p><span>03</span><p>Keep the introduction short. Let the music do the work.</p></div>
      </div>
      <form className="demoForm" onSubmit={e=>{e.preventDefault();if(ready)window.location.href=`mailto:${demoEmail}?subject=${subject}&body=${body}`}}>
        <div className="demoField"><label>ARTIST NAME</label><input value={artist} onChange={e=>setArtist(e.target.value)} placeholder="Your artist name" required/></div>
        <div className="demoField"><label>TRACK TITLE</label><input value={track} onChange={e=>setTrack(e.target.value)} placeholder="Track title" required/></div>
        <div className="demoField"><label>PRIVATE STREAMING LINK</label><input type="url" value={link} onChange={e=>setLink(e.target.value)} placeholder="https://" required/></div>
        <div className="demoField"><label>SHORT INTRO <i>OPTIONAL</i></label><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="A few lines about you and the record." rows="5"/></div>
        <button className="demoSend" type="submit" disabled={!ready}><span>PREPARE DEMO EMAIL</span><ArrowUpRight size={24}/></button>
        <p className="demoFine">This opens your email app with the submission addressed to {demoEmail}. Your audio is not uploaded to this website.</p>
      </form>
    </section>
  </>}
function FeatureGrid(){return <section className="world"><Link to="/mixes"><small>03 / BROADCASTS</small><h2>RADIO<br/>+ MIXES</h2><ArrowUpRight/></Link><Link to="/events"><small>04 / IRL</small><h2>EVENTS</h2><ArrowUpRight/></Link><Link className="acid" to="/music"><small>05 / CATALOGUE</small><h2>SELECTIONS</h2><ArrowUpRight/></Link></section>}
function DemoCTA(){return <section className="demo"><small>DEMO SUBMISSIONS</small><h2>YOUR MUSIC BELONGS HERE</h2><div><p>Send us something we can't ignore. Fresh talent and forward-thinking house music.</p><Link className="button dark" to="/demos">SUBMIT YOUR DEMO <ArrowUpRight/></Link></div></section>}
function NotFound(){return <PageHead n="404" kicker="SIGNAL LOST"><p>THAT TRANSMISSION DOESN'T EXIST. <Link to="/">RETURN HOME →</Link></p></PageHead>}
function Footer(){return <footer><h2>KEEP<br/>DANCING.</h2><div><img className="footerLogo" src={spacediscoLogo} alt="Spacedisco Records"/><p>Independent house music from Earth + beyond.</p><p>INSTAGRAM · SOUNDCLOUD · SPOTIFY · YOUTUBE</p><small>© 2026 SPACEDISCO RECORDS · TORONTO / WORLDWIDE</small></div></footer>}
function App(){return <HashRouter><Header/><Routes><Route path="/" element={<Home/>}/><Route path="/music" element={<Music/>}/><Route path="/music/:slug" element={<Release/>}/><Route path="/artists" element={<Artists/>}/><Route path="/artists/:slug" element={<Artist/>}/><Route path="/events" element={<Events/>}/><Route path="/mixes" element={<Mixes/>}/><Route path="/demos" element={<Demos/>}/><Route path="*" element={<NotFound/>}/></Routes><Footer/></HashRouter>}
createRoot(document.getElementById('root')).render(<App/>);