import React from 'react';import{createRoot}from'react-dom/client';import{ArrowUpRight,Play,Menu}from'lucide-react';import{releases,artists}from'./data/content';import'./styles.css';
const A=({children,href='#'})=><a href={href}>{children}</a>;
function App(){return <main><nav><div className="brand">◉ SPACEDISCO<small>RECORDS</small></div><div className="navlinks"><A>Music</A><A>Artists</A><A>Events</A><A>Mixes</A><A>Demos</A></div><Menu/></nav>
<section className="hero"><div className="eyebrow">INDEPENDENT HOUSE MUSIC · TORONTO · EST. 2006</div><h1>SPACE<br/>DISCO<span>®</span></h1><div className="heroBottom"><p>HOUSE MUSIC<br/>FROM EARTH + BEYOND.</p><div className="current"><small>CURRENT TRANSMISSION / SDR528</small><h2>HATIRAS<br/>PARTY G</h2><button><Play size={18} fill="currentColor"/> PLAY PREVIEW</button></div></div><div className="orbit"></div></section>
<div className="ticker"><div>SDR528 / HATIRAS / PARTY G / OUT NOW / SPACEDISCO RECORDS / TORONTO / KEEP DANCING / &nbsp; SDR528 / HATIRAS / PARTY G / OUT NOW /</div></div>
<section className="section"><header><div><small>01 / CATALOGUE</small><h2>NEW SIGNALS</h2></div><A>EXPLORE ALL <ArrowUpRight/></A></header><div className="releaseGrid">{releases.map((r,i)=><article className="release" key={r.catalog}><div className={'cover c'+i}><span>{r.catalog}</span><b>{r.artist}<br/>{r.title}</b></div><small>{r.catalog}</small><h3>{r.artist}</h3><p>{r.title}</p></article>)}</div></section>
<section className="artists section"><header><div><small>02 / ROSTER</small><h2>ARTISTS</h2></div></header><div className="artistList">{artists.map((a,i)=><A key={a}><span>0{i+1}</span>{a}<ArrowUpRight/></A>)}</div></section>
<section className="world"><div><small>03 / BROADCASTS</small><h2>RADIO<br/>+ MIXES</h2><ArrowUpRight/></div><div><small>04 / IRL</small><h2>EVENTS</h2><ArrowUpRight/></div><div className="acid"><small>05 / CURATED BY HATIRAS</small><h2>SELECTIONS</h2><ArrowUpRight/></div></section>
<section className="demo"><small>DEMO SUBMISSIONS</small><h2>YOUR MUSIC<br/>BELONGS HERE?</h2><div><p>Send us something we can't ignore. Fresh talent and forward-thinking house music.</p><button>SUBMIT YOUR DEMO <ArrowUpRight/></button></div></section>
<footer><h2>KEEP<br/>DANCING.</h2><div><b>SPACEDISCO® RECORDS</b><p>Independent house music from Earth + beyond.</p><p>INSTAGRAM · SOUNDCLOUD · SPOTIFY · YOUTUBE</p><small>© 2026 SPACEDISCO RECORDS · TORONTO / WORLDWIDE</small></div></footer></main>}createRoot(document.getElementById('root')).render(<App/>);